# Generated by Django 5.2.3 on 2025-07-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='created_date',
        ),
    ]
